version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: game
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: game
      ROUND_DURATION: ${ROUND_DURATION:-60}
      COOLDOWN_DURATION: ${COOLDOWN_DURATION:-30}
      JWT_SECRET: ${JWT_SECRET:-secret}
    depends_on:
      - db
  frontend:
    build: ./frontend
    depends_on:
      - backend
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
