version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: game
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: game
      ROUND_DURATION: ${ROUND_DURATION:-60}
      COOLDOWN_DURATION: ${COOLDOWN_DURATION:-30}
      JWT_SECRET: ${JWT_SECRET:-secret}
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
